import structlog
from src.agents.state import PRReviewState
from src.azure_client.pr_client import create_pull_request, post_pr_comment
from src.config.settings import settings

log = structlog.get_logger()


def _agent_pr_description(state: PRReviewState) -> str:
    """Builds the PR description for the agent-created PR."""
    from src.agents.nodes.publish_review import _findings_table

    lines = []
    lines.append("## AI Review Agent — Automated Fix PR")
    lines.append("")
    lines.append(
        f"This PR was automatically created by the AI Review Agent "
        f"based on issues found in the original PR: {state.pr_url}"
    )
    lines.append("")
    if state.pr_author_id and state.pr_author_name:
        mention = f"@<{state.pr_author_id}>"
        lines.append(f"{mention} — please review these changes before merging.")
    else:
        lines.append("Developer — please review these changes before merging.")
    lines.append("")
    lines.append("### What was fixed")
    lines.append("")
    findings = state.refined_findings if state.refined_findings else state.findings
    if findings:
        _findings_table(findings, lines)
    else:
        lines.append("No specific findings recorded.")
    lines.append("")
    lines.append("### CI Status")
    lines.append("")
    lines.append(state.aider_fix_summary)
    lines.append("")
    lines.append("---")
    lines.append("*Generated by AI Review Agent | Amazon Bedrock Nova Pro + Aider*")
    return "\n".join(lines)


async def run(state: PRReviewState) -> dict:
    """
    Creates the agent PR on ADO and posts a link-back comment on the original PR.
    Only runs if the agent actually made and pushed changes.
    """
    log.info("create_agent_pr_start", agent_branch=state.agent_branch)

    if not state.agent_branch or not state.aider_fix_applied:
        log.info("create_agent_pr_skipped_no_changes")
        return {"agent_pr_url": "", "status": "DONE"}

    developer_branch = state.source_branch.replace("refs/heads/", "")

    try:
        pr_title = f"[AI Fix] Automated fixes for PR #{state.pr_id}"
        pr_description = _agent_pr_description(state)
        reviewer_ids = [state.pr_author_id] if state.pr_author_id else []

        try:
            agent_pr = await create_pull_request(
                repository_id=state.repository_id,
                source_branch=state.agent_branch,
                target_branch=developer_branch,
                title=pr_title,
                description=pr_description,
                reviewer_ids=reviewer_ids,
            )
        except Exception as api_err:
            log.warning("create_agent_pr_with_reviewers_failed", error=str(api_err))
            log.info("create_agent_pr_fallback_no_reviewers")
            # Fallback: create the PR without reviewers (the @mention comment will still notify them)
            agent_pr = await create_pull_request(
                repository_id=state.repository_id,
                source_branch=state.agent_branch,
                target_branch=developer_branch,
                title=pr_title,
                description=pr_description,
                reviewer_ids=[],
            )
        agent_pr_id = agent_pr.get("pullRequestId", "")
        org = settings.AZURE_DEVOPS_ORG
        project = settings.AZURE_DEVOPS_PROJECT
        repo = state.repository_id
        agent_pr_url = f"https://dev.azure.com/{org}/{project}/_git/{repo}/pullrequest/{agent_pr_id}"
        log.info("create_agent_pr_created", pr_id=agent_pr_id, url=agent_pr_url)

        author_mention = f"@<{state.pr_author_id}>" if (state.pr_author_id and state.pr_author_name) else "Developer"
        link_comment = (
            f"## AI Review Agent — Fix Branch Ready\n\n"
            f"{author_mention} — The AI Review Agent has analysed this PR and applied fixes "
            f"on a **separate protected branch** to keep your branch safe.\n\n"
            f"**Agent PR:** {agent_pr_url}\n\n"
            f"Please review the changes in the agent PR and merge them into your branch "
            f"`{developer_branch}` when satisfied.\n\n"
            f"**Summary:** {state.aider_fix_summary}"
        )
        await post_pr_comment(state.repository_id, state.pr_id, link_comment)
        log.info("create_agent_pr_comment_posted", original_pr_id=state.pr_id)
        return {"agent_pr_url": agent_pr_url, "status": "DONE"}

    except Exception as e:
        import traceback
        log.error("create_agent_pr_error", error=str(e), traceback=traceback.format_exc())
        # Don't crash the pipeline — log and continue to publish_review
        return {"agent_pr_url": "", "status": "DONE", "error": f"Agent PR creation failed: {e}"}